server:
  port: 50000

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:43000}/${DB_NAME:vivo}
    username: raver
    password: raver
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    consumer:
      group-id: order-group
      auto-offset-reset: latest
